### ISSUE TITLE
Media Library broken

### ISSUE THREAD

**Issue by judy-zz** [DigitPaint/skyline#5]
When I attempt to visit the media library with the latest development version, the page fails to load. I get the red "Loading" in the topleft corner, but I get 4 javascript errors, and I never get to see the interface.

I've bisected it back to this commit:
290fbdc3cac3bdb66e91d8c1a61b7dd138badbaf
Implement the new media library in main development branch

Here are the javascript errors I get, copied from the Firebug interface:
Application.Layout.Media.initializeTree is not a function
Application.Layout.Media.initializeTree("dirtree");
dirs (line 101)
Skyline.Table is not a constructor
var t = new Skyline.Table(f, {draggable: true, droppables: ".dir"});
dirs (line 180)
element is null
layout = element.retrieve("skyline.layout");
skyline.js (line 604)
Application.Layout.Media.initializeUploadPanel is not a function
Application.Layout.Media.initializ...Panel("/skyline/media/dirs/1/files");
